spring.application.name=JavaNotifications

spring.datasource.url=jdbc:postgresql://localhost:5431/email_requests
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
